### ISSUE TITLE
how to close a session?

### ISSUE THREAD

**Issue by huguesfontenelle** [mrkrd/matlab_wrapper#10]
```
matlab = matlab_wrapper.MatlabSession(
                options='-nojvm',
                buffer_size=1000,
            )
matlab.put('x', 4.6)
matlab.eval('y=4*x')
y=matlab.get('y')
```

How do I then close the session?
Something like:
```
matlab.close()
```
would be useful.

I tried `options='-nojvm -nodesktop -nodisplay -nosplash'` which is "quieter" but the Matlab process still exist.
I could try to kill it, but surely there is a better way?

**Comment by mrkrd** [comment]
You can try:

  del matlab

**Comment by huguesfontenelle** [comment]
That works, thanks.
