### ISSUE TITLE
dimension of cellarrays

### ISSUE THREAD

**Issue by andrescodas** [mrkrd/matlab_wrapper#19]
Hi,

   There are issues when converting a cell array with matrices of the same size from matlab to python. The shape of the cell elements are interpreted together with the shape of the cell itself. Then there is a bug on the reshape command.

   You implemented a fix for this case for the conversion of structs but not for the cell arrays.

   I recommend you to implement the handling of cells in this way:

    elif class_name == 'cell':
        out = np.empty(numelems,dtype='O')
        for i in range(numelems):
            cell = libmx.mxGetCell(pm, i)

            if bool(cell):
                out[i] = mxarray_to_ndarray(libmx, cell)
            else:
                ### uninitialized cell
                out[i] = None
          
        out = out.reshape(dims[:ndims], order='F')
        out = out.squeeze()

**Comment by mrkrd** [comment]
Thanks for opening the issues.  I'll check them over the weekend.

**Comment by mrkrd** [comment]
> Hi,
>
>    There are issues when converting a cell array with matrices of the same size from matlab to python. The shape of the cell elements are interpreted together with the shape of the cell itself. Then there is a bug on the reshape command.
>
>    You implemented a fix for this case for the conversion of structs but not for the cell arrays.
>
>    I recommend you to implement the handling of cells in this way:
>
>     elif class_name == 'cell':
>         out = np.empty(numelems,dtype='O')
>         for i in range(numelems):
>             cell = libmx.mxGetCell(pm, i)
>
>             if bool(cell):
>                 out[i] = mxarray_to_ndarray(libmx, cell)
>             else:
>                 ### uninitialized cell
>                 out[i] = None
>
>         out = out.reshape(dims[:ndims], order='F')
>         out = out.squeeze()

Good catch.  Could you make a PR with an small test function in
test_matlab.py ?

Thanks!
