### ISSUE TITLE
How to run .py file in different directory

### ISSUE THREAD

**Issue by LizzzMax** [mrkrd/matlab_wrapper#26]
I find that the python file must be placed in the same directory as .m file ,or the program can't find the .m file, so is there any solution to run python file in different directory?

**Comment by mrkrd** [comment]
>I find that the python file must be placed in the same directory as .m
>file ,or the program can't find the .m file, so is there any solution
>to run python file in different directory? 


The m file has to be in the matlabpath.

**Comment by LizzzMax** [comment]
@mrkrd  Thank you for your answer,but I still don't know how to do, could you explain more specific? What code I should add in python file

**Comment by LizzzMax** [comment]
@mrkrd  Thank you for your answer,but I still don't know how to do, could you explain more specific? 
For example, my .m files are  in  '/matlab', and my python files are in '/python'
What code I should add in python file to make '/matlab' be in the matlabpath? Or I just need to  add the '/matlab' to the matlabpath in matlab?

**Comment by mrkrd** [comment]
> @mrkrd  Thank you for your answer,but I still don't know how to do, could you explain more specific? 
> For example, my .m files are  in  '/matlab', and my python files are in '/python'
> What code I should add in python file to make '/matlab' be in the matlabpath? Or I just need to  add the '/matlab' to the matlabpath in matlab?

You have to make sure that MATLAB can find the m-files.  It has nothing
to do with matlab_wrapper or Python.  Please check MATLAB's
documentation on `path` and `addpath`.

Hope that help! :-)

**Comment by LizzzMax** [comment]
@mrkrd  Thank you!

**Comment by LizzzMax** [comment]
@mrkrd  Thank you!
