### ISSUE TITLE
Launching multiple instances of MATLAB

### ISSUE THREAD

**Issue by lrq3000** [mrkrd/matlab_wrapper#28]
I have a script that once launched in MATLAB runs in single core, so the idea would be to launch multiple instances (on different inputs) to take advantage of parallelism.

However, it seems by default this library will connect to the same MATLAB instance that was spawned by the earliest launch.

Is it possible to configure the module to launch a different instance of MATLAB?

**Comment by mrkrd** [comment]
> I have a script that once launched in MATLAB runs in single core, so the idea would be to launch multiple instances (on different inputs) to take advantage of parallelism.
>
> However, it seems by default this library will connect to the same MATLAB instance that was spawned by the earliest launch.
>
> Is it possible to configure the module to launch a different instance of MATLAB?

First check, if you can start multiple MATLAB sessions by hand outside
of Python/matlab_wrapper.  There might be some limitations in your
MATLAB license.

Second, every instance of MatlabSession should spawn a separate MATLAB
engine.  Make sure that you are generating multiple MatlabSession
objects.

Third, if it does not work, you can wrap MatlabSession in a function and
start multiple instances using multiprocessing.  It should work, because
multiprocessing forks a separate Python process for each worker.

**Comment by lrq3000** [comment]
Sorry for the late reply. The idea was to launch a different MatlabSession from different instances of the same script (so from 2 different python processes). Currently, if I try to launch multiple sessions, from either the same instance or from 2 different instances, here is what happens for the 2nd launch:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-558e50de9e0a> in <module>()
      2 import re
      3 # start a Matlab session
----> 4 mlab = matlab_wrapper.MatlabSession()
      5 # add current folder to the path to have access to helper .m scripts, this needs to be done before each command call
      6 #mlab.workspace.addpath(filestr_to_raw(os.path.dirname(os.path.abspath(__file__))))

C:\Users\AI\Anaconda2\lib\site-packages\matlab_wrapper\matlab_session.pyc in __init__(self, options, matlab_root, buffer_size)
    111         self._matlab_root = matlab_root
    112 
--> 113         engine, libeng, libmx, version = load_engine_and_libs(matlab_root, options)
    114 
    115         self._libeng = libeng

C:\Users\AI\Anaconda2\lib\site-packages\matlab_wrapper\matlab_session.pyc in load_engine_and_libs(matlab_root, options)
    309             lib_dir = join(matlab_root, "bin", "win32")
    310 
--> 311         check_python_matlab_architecture(bits, lib_dir)
    312 
    313         ## We need to modify PATH, to find MATLAB libs

C:\Users\AI\Anaconda2\lib\site-packages\matlab_wrapper\matlab_session.pyc in check_python_matlab_architecture(bits, lib_dir)
    367     """Make sure we can find corresponding installation of Python and MATLAB."""
    368     if not os.path.isdir(lib_dir):
--> 369         raise RuntimeError("It seem that you are using {bits} version of Python, but there's no matching MATLAB installation in {lib_dir}.".format(bits=bits, lib_dir=lib_dir))
    370 
    371 

RuntimeError: It seem that you are using 64bit version of Python, but there's no matching MATLAB installation in C:\Program Files\MATLAB\R2018a\bin\bin\win64.
```

This RuntimeError is not specific to IPython.

**Comment by mrkrd** [comment]
1. Make sure you can run multiple instances MATLAB (without Python and
matlab_wrapper).

2. Check CONTRIBUTING guidelines and write more about your versions.

3. This exception looks strange:

> C:\Users\AI\Anaconda2\lib\site-packages\matlab_wrapper\matlab_session.pyc in check_python_matlab_architecture(bits, lib_dir)
>     367     """Make sure we can find corresponding installation of Python and MATLAB."""
>     368     if not os.path.isdir(lib_dir):
> --> 369         raise RuntimeError("It seem that you are using {bits} version of Python, but there's no matching MATLAB installation in {lib_dir}.".format(bits=bits, lib_dir=lib_dir))

This line has to do only with verifying a path.  You need to debug it
and find out why the value of lib_dir is different for the 1st and 2nd
instance of MatlabSession.
