### ISSUE TITLE
Error when getting empty Matlab object

### ISSUE THREAD

**Issue by jeremymoreau** [mrkrd/matlab_wrapper#6]
I am using a Matlab software package that stores data in struct arrays. These struct arrays contain a variety of other object types (other struct arrays, cell arrays, doubles, chars, etc.), which sometime turn out to be empty (i.e. they have a field name but no associated value). Using matlab_wrapper's get() method to access an empty object (whether it be contained in another struct or not) results in the following error:
```
matlab_wrapper/matlab_session.pyc in get(self, name)
    198         pm = self._libeng.engGetVariable(self._ep, name)
    199 
--> 200         out = mxarray_to_ndarray(self._libmx, pm)
    201 
    202 

matlab_wrapper/matlab_session.pyc in mxarray_to_ndarray(libmx, pm)
    647 
    648                 if bool(field):
--> 649                     el = mxarray_to_ndarray(libmx, field)
    650                 else:
    651                     ### uninitialized cell

matlab_wrapper/matlab_session.pyc in mxarray_to_ndarray(libmx, pm)
    674             new_arrays.append(newarr)
    675 
--> 676         if len(new_arrays) == 0:
    677             new_arrays.append(None)
    678         out = np.rec.fromarrays(new_arrays, names=field_names)

numpy/core/records.pyc in fromarrays(arrayList, dtype, shape, formats, names, titles, aligned, byteorder)
    520 
    521     if shape is None or shape == 0:
--> 522         shape = arrayList[0].shape
    523 
    524     if isinstance(shape, int):

IndexError: list index out of range
```

Here is a simple example to reproduce the issue:
```python
import matlab_wrapper

matlab = matlab_wrapper.MatlabSession()
matlab.eval("empty_struct = struct('')")
empty_struct = matlab.get("empty_struct")
```

I've managed to resolve the issue by simply appending an empty tuple to ```arrays``` when it is empty (lines 662-663) in [this gist] (https://gist.github.com/jeremymoreau/f8d67b72fae24258c1f1), but you may have a better idea of how to fix this, so I'm just posting this as an issue.

For reference, I'm running Matlab 2014b 64 bits on Debian 6.0.8.

Really nice library, btw!

**Comment by mrkrd** [comment]
Hi, I have just commited a fix.

I have implemented it little differently, because appending an empty
tuple was resulting in an empty record array with a single field called
'f0'.  Empty Numpy array seemed to be closer to `0x0 struct array with
no fields`.

Thank you again for the great report!

Cheers
Marek

**Comment by jeremymoreau** [comment]
Thanks for fixing this so quickly!

Your solution is indeed much nicer.

Cheers and best wishes for 2015,
Jeremy
