### ISSUE TITLE
how can run .m files

### ISSUE THREAD

**Issue by mallakimahdi** [mrkrd/matlab_wrapper#8]
how can create matlab session object then run a .m file on it?

**Comment by mrkrd** [comment]
mahdi <notifications@github.com> writes:

> how can create matlab session object then run a .m file on it?

Please check example file eval_m_file.py [1]

Let me know, if you have more questions.

Cheers
Marek


[1] https://github.com/mrkrd/matlab_wrapper/blob/master/examples/eval_m_file.py
