### ISSUE TITLE
path for functions outside current directory

### ISSUE THREAD

**Issue by huguesfontenelle** [mrkrd/matlab_wrapper#9]
It seems that I must start python in the same directory where the *.m files are.

For example:
```
import matlab_wrapper
matlab = matlab_wrapper.MatlabSession()
matlab.eval('my_script.m')
```
works well when `my_script.m` is in the current dir.

If I start `python` or `ipython` one directory up, I get:
```
RuntimeError: Error from MATLAB
MATLAB:undefinedVarOrFunction: Undefined variable "my_script" or function "my_script.m".
```

I thought about a couple of workarounds:
```
import os
os.chdir('examples')
```

or
```
matlab.eval('addpath("/path/to/code/examples");')
```
or
```
matlab.eval('addpath /path/to/code/examples')
```
but neither work on my MacOS 10.9.5, Matlab R2013b 64bits, Python 2.7.9, iPython 3.0.0

**Comment by huguesfontenelle** [comment]
Solution that works:
`matlab.eval('addpath \path\to\code\examples')`

or
`matlab.eval('addpath ' + PATH_TO_LIB)`

with PATH_TO_LIB properly defined in python of course.

**Comment by huguesfontenelle** [comment]
I thought that I had a workaround previously (addpath) but no, I still get the following error:
```
RuntimeError: MATLAB function <_FuncPtr object at 0x1125f27a0> failed
(<matlab_wrapper.matlab_session.LP_mxArray object at 0x112618ef0>) with arguments:
(<matlab_wrapper.matlab_session.LP_Engine object at 0x10ed61d40>, 'ERRSTR__')
```

**Comment by mrkrd** [comment]
Hi, I can look into this next week. If it's really a matter of MATLAB path, then you also could try to set MATLABPATH environment variable. See MATLAB documentations for the details.

Marek

**Comment by huguesfontenelle** [comment]
Actually that particular path was already in my MATLABPATH.
But even trying to add a new path fails.

**Comment by mrkrd** [comment]
addpath("/path/to/code/examples");

will not work, because `"` is not recognized.

Please note that the original error (m-file not found) is different than the second one (function failed).

I would suggest to set MATLABPATH correctly and test it by starting MATLAB in a different directory then the m-files.

You could also test it with a very small m-file script/function and see if it works.

Let me know, if you have any progress. Thanks!

**Comment by huguesfontenelle** [comment]
Correct, it's a typo in my post. I meant of course
```
matlab.eval("addpath('/path/to/code/examples');")
```

**Comment by mrkrd** [comment]
Hugues Fontenelle <notifications@github.com> writes:

> Actually that particular path was already in my MATLABPATH.
> But even trying to add a new path fails.

Please provide a self-contained reproducible example.  If I'm not able
to reproduce on my machine, I cannot do much about it.

Eventually, you could try to debug it yourself.  matlab_wrapper it's
really a rather simple library.

Cheers,
Marek

**Comment by mrkrd** [comment]
Hugues Fontenelle <notifications@github.com> writes:

> I thought that I had a workaround previously (addpath) but no, I still get the following error:
> ```
> RuntimeError: MATLAB function <_FuncPtr object at 0x1125f27a0> failed
> (<matlab_wrapper.matlab_session.LP_mxArray object at 0x112618ef0>) with arguments:
> (<matlab_wrapper.matlab_session.LP_Engine object at 0x10ed61d40>, 'ERRSTR__')
> ```

I noticed that it's a similar error as in the issue #11.

Therefore, it might not have anything to do with MATLABPATH.

Please tell me, if you can run example scripts that come with
matlab_wrapper without errors.

**Comment by huguesfontenelle** [comment]
The example *was* in the first post of this thread, but now I can run it without error. I just don't get it.
The test suite results are in #11 . Feel free to close this thread.

**Comment by yangxiu008** [comment]
hi huguesfontenelle:
I have a similar issue to yours. I tried to run the eval_m_file.py in the example. but there is an error.

>>> matlab.eval('my_script')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\matlab_wrapper\matlab_session.py", line 181, in eval
raise RuntimeError("Error from MATLAB\n{0}".format(error_string))


I add "run" before "my_script". it seems ok.it goes like this matlab.eval("run(c:\...\my_script.m)").
do you have any idea?  do you have a way to remove "run"?

**Comment by mrkrd** [comment]
From the documentation of `run':

  RUN is a convenience function that runs scripts that are not currently on the path.

You need to have my_script.m in MATLAB's path.  Otherwise `run' is the same as just calling the script by its name.
